inherit_from: .rubocop_todo.yml

# RuboCop configuration
# See: https://docs.rubocop.org/rubocop/configuration.html

plugins:
  - rubocop-rspec

Metrics/MethodLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
