[tools]
ruby = "3.4.4"
lazygit = "latest"
gh = "latest"
bun = "latest"
claude = "latest"

[env]
OBSIDIAN_VAULT_PATH = "../obsidian-test-notes/notes"

[tasks.bundle]
description = "Install project dependencies"
run = [
    "bundle install"
]

[tasks.dev]
description = "Start the Obsidian MCP server with sample vault"
run = [
    "./obsidian_server.rb"
]

[tasks."rubocop:fix"]
description = "Fix RuboCop errors automatically"
run = [
    "bundle exec rubocop --autocorrect-all"
]

[tasks."rubocop:todo-update"]
description = "Update RuboCop todo list with current violations"
run = [
    "bundle exec rubocop --auto-gen-config"
]

[tasks."docker:build"]
description = "Build the production Docker image"
run = [
    "docker build -t obsidian-mcp-server ."
]

[tasks."docker:build:dev"]
description = "Build the development Docker image"
run = [
    "docker build -f Dockerfile.dev -t obsidian-mcp-server:dev ."
]

[tasks."mcp:inspect"]
description = "Inspect the MCP server"
depends = ["docker:build:dev"]
run = '''
    bunx --bun @modelcontextprotocol/inspector \
    docker run -i --rm -v $OBSIDIAN_VAULT_PATH:/vault \
    obsidian-mcp-server:dev
'''
